language: android
jdk: oraclejdk8
sudo: false

android:
  components:
    - platform-tools
    - tools
    - build-tools-24.0.2
    - android-22
    - android-24
    - sys-img-armeabi-v7a-android-22
    - extra-android-m2repository
deploy:
  provider: releases
  user: "plexpt"
  password: "a88073597"
  file: app/build/outputs/apk/app-release.apk
  skip_cleanup: true
  on:
    tags: true

script: ./gradlew connectedAndroidTest
