language: android
jdk: oraclejdk8
sudo: false

android:
  components:
    - platform-tools
    - tools
    - build-tools-24.0.2
    - android-22
    - android-24
    - sys-img-armeabi-v7a-android-22
    - extra-android-m2repository
     - extra-android-suppo

script:
  - "./gradlew assembleRelease"
  
deploy:
  provider: releases
   api_key:b6712c1e536512b5a0526478b5d1f21f4669ef32
  file: app/build/outputs/apk/app-release.apk
  skip_cleanup: true
  on:
    tags: true

